### ISSUE TITLE
Closing the widget dialog on the same tick as it opens causes the counter not to update.

### ISSUE THREAD

**Issue by WolffTech** [WolffTech/coal-bag-addon#4]
As pointed out by Keyosk
>One thing to note, there's an edge case I was unable to solve for, I looked into var and pbits and was unable to see an alternative to following chat and widget messages, but there's a possibility to close the Widget dialog on the same tick as it opens. onGameTick misses the widget and message in this scenario.

>When doing blast furnace for a few hours I was able to see this happen a few times when my clicks were occurring really fast. Checking the bag or attempting to empty the bag following that will get you the right message and 0 quantity.

I can't really think of any way to get around this, so any suggestions are welcome.

**Comment by iChillieman** [comment]
Have you tried calling your logic in a onClientTick function, instead of onGameTick?

**Comment by WolffTech** [comment]
It seems that `onGameTick` updates every 600ms while `onClientTick` updates every 20ms. I don't know how fast you can actually close the widget, but seems like it'll work for now. I tested it out and can't seem to reproduce the issue with the change made.  I'll make the changes and update the plugin. Thank you for the suggestion!
